export const options = [
    {
        id: 1,
        numbergu45: 12345,
        page: "Page 1",
        feedtype: "Coal",
        cargo: "Anthracite",
        branchowner: "UzRailCargo",
        vagon: "Vagon 12-345",
        datecreate: "2025-07-20",
        author: "Jahongir X.",
        numbergu46: 54321,
        numberfdu92: 67890,
        status: "Approved",
        comment: "All documents verified."
    },
    {
        id: 2,
        numbergu45: 12346,
        page: "Page 2",
        feedtype: "Oil",
        cargo: "Diesel",
        branchowner: "TransOil",
        vagon: "Vagon 98-231",
        datecreate: "2025-07-21",
        author: "Murod S.",
        numbergu46: 54322,
        numberfdu92: 67891,
        status: "Pending",
        comment: "Awaicsaaaaaaaaaaaaaaaaaaaaaating approval."
    },
    {
        id: 3,
        numbergu45: 12347,
        page: "Page 3",
        feedtype: "Grain",
        cargo: "Wheat",
        branchowner: "AgroTrans",
        vagon: "Vagon 11-876",
        datecreate: "2025-07-22",
        author: "Aziza T.",
        numbergu46: 54323,
        numberfdu92: 67892,
        status: "Approved",
        comment: "Grain quality checked."
    },
    {
        id: 4,
        numbergu45: 12348,
        page: "Page 4",
        feedtype: "Chemical",
        cargo: "Fertilizer",
        branchowner: "ChemLogistics",
        vagon: "Vagon 24-999",
        datecreate: "2025-07-23",
        author: "Bekzod N.",
        numbergu46: 54324,
        numberfdu92: 67893,
        status: "Rejected",
        comment: "Incomplete documentation."
    },
    {
        id: 5,
        numbergu45: 12349,
        page: "Page 5",
        feedtype: "Wood",
        cargo: "Timber",
        branchowner: "ForestRail",
        vagon: "Vagon 45-322",
        datecreate: "2025-07-24",
        author: "Nilufar K.",
        numbergu46: 54325,
        numberfdu92: 67894,
        status: "Approved",
        comment: "Shipment cleared."
    },
    {
        id: 6,
        numbergu45: 12350,
        page: "Page 6",
        feedtype: "Metal",
        cargo: "Steel coils",
        branchowner: "MetalCargo",
        vagon: "Vagon 55-789",
        datecreate: "2025-07-25",
        author: "Farrukh R.",
        numbergu46: 54326,
        numberfdu92: 67895,
        status: "Pending",
        comment: "Verification in progress."
    },
    {
        id: 7,
        numbergu45: 12351,
        page: "Page 7",
        feedtype: "Textile",
        cargo: "Cotton",
        branchowner: "TextileTrans",
        vagon: "Vagon 33-223",
        datecreate: "2025-07-26",
        author: "Dilnoza Y.",
        numbergu46: 54327,
        numberfdu92: 67896,
        status: "Approved",
        comment: "High-priority shipment."
    },
    {
        id: 8,
        numbergu45: 12352,
        page: "Page 8",
        feedtype: "Machinery",
        cargo: "Excavator parts",
        branchowner: "TechTransport",
        vagon: "Vagon 77-654",
        datecreate: "2025-07-27",
        author: "Islom A.",
        numbergu46: 54328,
        numberfdu92: 67897,
        status: "In Transit",
        comment: "ETA: 3 days."
    },
    {
        id: 9,
        numbergu45: 12353,
        page: "Page 9",
        feedtype: "Liquid",
        cargo: "Alcohol",
        branchowner: "BevLogistics",
        vagon: "Vagon 88-100",
        datecreate: "2025-07-28",
        author: "Shahlo M.",
        numbergu46: 54329,
        numberfdu92: 67898,
        status: "Approved",
        comment: "Customs cleared."
    },
    {
        id: 10,
        numbergu45: 12354,
        page: "Page 10",
        feedtype: "Construction",
        cargo: "Cement",
        branchowner: "BuildRail",
        vagon: "Vagon 66-321",
        datecreate: "2025-07-29",
        author: "Jasur H.",
        numbergu46: 54330,
        numberfdu92: 67899,
        status: "Pending",
        comment: "Documents being prepared."
    }
];