import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import DashboardComp from "@/components/DashboardComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Task of Uzbekistan Railways",
  description: "Generated by Task of Uzbekistan Railways",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className=" w-full sticky top-0 z-20">
          <Navbar />
        </div>
        <div className=" w-full flex justify-center gap-0 border-collapse">
          <div className=" w-[10%] sticky top-0 z-10 ">
            <DashboardComp />
          </div>
          <div className=" w-[90%]">
            {children}  
          </div>
        </div>
      </body>
    </html>
  );
}
