import React from "react";
import ListGU45 from "./list-gu45/page";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Task of Uzbekistan Railways",
    description: "Generated by Task of Uzbekistan Railways",
};

export default function DashboardPage() {

    return (
        <React.Fragment>
            <ListGU45 />
        </React.Fragment>
    );
}
